
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: cd server && npm ci --no-audit && npm run lint --if-present && npm run build --if-present && cd ..
      env:
        CI: true
